/*
 * macOS backend: Apple NaturalLanguage (NLLanguageRecognizer).
 *
 * Implements the ABI declared in zlang_bridge.h. The header is imported via
 * swiftc -import-objc-header, so ZlangHypothesis, ZLANG_TAG_CAP and the
 * ZLANG_ERR_* constants below are generated by clang from that single source
 * of truth — they are not redeclared here.
 *
 * No algorithm lives in this file. Every language decision comes from the OS
 * model; this is marshalling only.
 */

import Foundation
import NaturalLanguage

/*
 * The score kind is a static C string the caller must not free.
 *
 * strdup once at first use: the allocation lives for the process lifetime,
 * which is exactly the contract in zlang_bridge.h. Returning a pointer into a
 * Swift String would dangle as soon as the String is released.
 */
private let scoreKindProbability: UnsafePointer<CChar> = {
    guard let copy = strdup("probability") else {
        fatalError("zlang: strdup failed for score kind")
    }
    return UnsafePointer(copy)
}()

/*
 * Writes a BCP 47 tag into the fixed-size `tag` field.
 *
 * C declares `char tag[24]`, which clang imports into Swift as a 24-element
 * tuple — there is no fixed-size array type in Swift. Rebinding the tuple's
 * address to CChar is the supported way to treat it as the byte buffer it
 * actually is.
 *
 * Returns false when the tag does not fit; the caller skips that slot rather
 * than writing a truncated tag that would look like a different language.
 */
private func writeTag(_ tag: String, into slot: UnsafeMutablePointer<ZlangHypothesis>) -> Bool {
    let capacity = Int(ZLANG_TAG_CAP)
    let bytes = Array(tag.utf8)

    // Need one byte left for the NUL terminator.
    guard bytes.count < capacity else { return false }

    withUnsafeMutablePointer(to: &slot.pointee.tag) { tuple in
        tuple.withMemoryRebound(to: CChar.self, capacity: capacity) { dst in
            // Zero the whole field first: guarantees NUL termination and leaves
            // no stale bytes from a previous call behind the terminator.
            dst.update(repeating: 0, count: capacity)
            for (index, byte) in bytes.enumerated() {
                dst[index] = CChar(bitPattern: byte)
            }
        }
    }

    return true
}

/*
 * NaturalLanguage.framework ships with macOS 10.14 and the deployment target
 * is at least that, so the framework is always present. The flag exists for
 * backends that can be switched off at runtime — the Windows ELS service can.
 */
@_cdecl("zlang_bridge_available")
public func zlang_bridge_available() -> Bool {
    return true
}

@_cdecl("zlang_bridge_score_kind")
public func zlang_bridge_score_kind() -> UnsafePointer<CChar> {
    return scoreKindProbability
}

@_cdecl("zlang_bridge_detect")
public func zlang_bridge_detect(
    _ utf8Text: UnsafePointer<CChar>?,
    _ maxResults: UInt32,
    _ out: UnsafeMutablePointer<ZlangHypothesis>?
) -> Int32 {
    // Constants from an anonymous C enum are imported as Swift `Int`, not Int32,
    // so the ABI's int32_t return type needs an explicit narrowing.
    guard let utf8Text = utf8Text, let out = out else {
        return Int32(ZLANG_ERR_BAD_ARG)
    }

    guard let text = String(validatingUTF8: utf8Text) else {
        return Int32(ZLANG_ERR_ENCODING)
    }

    // The caller owns the buffer and told us how big it is; never write past it.
    let capacity = Int(min(max(maxResults, 1), UInt32(ZLANG_MAX_RESULTS)))

    let recognizer = NLLanguageRecognizer()
    recognizer.processString(text)

    /*
     * languageHypotheses returns a dictionary, which has no order. The ABI
     * promises `out` is sorted by descending likelihood, so sort here — the
     * Rust and JS layers above rely on position alone once confidence is null
     * on other backends.
     */
    let ranked = recognizer
        .languageHypotheses(withMaximum: capacity)
        .sorted { $0.value > $1.value }

    var written = 0
    for (language, confidence) in ranked {
        if written == capacity { break }

        // rawValue is the BCP 47 tag as Apple reports it ('vi', 'zh-Hans').
        // Passed through untouched: normalising tags is a decision for the
        // layer that knows what it wants, not for this bridge.
        guard writeTag(language.rawValue, into: out + written) else { continue }

        out[written].confidence = confidence
        written += 1
    }

    // 0 is a valid answer: the text was too short or too ambiguous to decide.
    return Int32(written)
}
